{
"error":"",
"extra":{
"archiveEndTime":"2022-12-19",
"needAuth":true,
"queryTitleMaxSize":15,
"sellerExport":"//tradearchive.taobao.com/trade/itemlist/list_export_order.htm",
"tjbPriority":0
},
"mainOrders":[
{
"buyer":{
"guestUser":false,
"id":2210725237200,
"memberUrl":"//member1.taobao.com/member/userProfile.jhtml?userID=tb8412379130&sign=8efd2664c0bfceefc4e844878df088f9",
"nick":"tb8412379130",
"operations":[
{
"action":"a14",
"imgUrl":"//gtd.alicdn.com/tps/i8/T1KNtuXc4rXXXXXXXX-12-12.png",
"style":"t0",
"title":"查询该买家订单",
"type":"operation",
"url":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1"
}
],
"phoneNum":"176********"
},
"extra":{
"batchSendGoods":1,
"currency":"CNY",
"currencySymbol":"￥",
"disableCheckbox":false,
"inHold":false,
"isShowSellerService":false,
"sellerFlag":0
},
"id":"1749141123495230072",
"operations":[

],
"orderInfo":{
"archive":true,
"b2C":true,
"createTime":"2022-11-24 23:59:31",
"id":"1749141123495230072"
},
"payInfo":{
"actualFee":"12.80",
"icons":[
{
"linkTitle":"该订单来自您的手机淘宝店铺",
"linkUrl":"http://www.taobao.com/go/act/integrated/maijia-index.php?sprefer=symj27",
"type":3,
"url":"//img.alicdn.com/tps/i1/T1xRBqXdNAXXXXXXXX-46-16.png"
}
],
"operations":[
{
"style":"t16",
"text":"查看物流",
"type":"operation",
"url":"//wuliu.taobao.com/user/order_detail_new.htm?trade_id=1749141123495230072&seller_id=1583809483"
}
],
"postType":"(含快递:￥0.00)"
},
"statusInfo":{
"operations":[
{
"params":{
"qianNiuPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749141123495230072",
"solutionPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749141123495230072"
},
"style":"t16",
"text":"详情",
"type":"operation",
"url":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749141123495230072"
}
],
"text":"交易成功",
"type":"t0"
},
"subOrders":[
{
"itemInfo":{
"extra":[
{
"name":"发货时间",
"value":"11月26日 00:00前发货",
"visible":"SOLID"
}
],
"itemUrl":"//trade.taobao.com/trade/detail/tradeSnap.htm?tradeID=1749141123495230072&snapShot=true",
"pic":"//img.alicdn.com/imgextra/i4/1583809483/O1CN01cymtDi2JvGg7YX3pv_!!1583809483.jpg_sum.jpg",
"serviceIcons":[
{
"linkTitle":"正品保证",
"linkUrl":"//rule.tmall.com/tdetail-4400.htm",
"name":"正品保证",
"title":"正品保证",
"type":3,
"url":"//img.alicdn.com/tps/i2/T1SyeXFpliXXaSQP_X-16-16.png"
},
{
"linkTitle":"如实描述",
"linkUrl":"//www.taobao.com/go/act/315/xfzbz_rsms.php?ad_id=&am_id=130011830696bce9eda3&cm_id=&pm_id=",
"name":"如实描述",
"title":"如实描述",
"type":3,
"url":"//img.alicdn.com/tps/TB1PDB6IVXXXXaVaXXXXXXXXXXX.png"
},
{
"linkTitle":"七天退换",
"linkUrl":"//pages.tmall.com/wow/seller/act/seven-day",
"name":"七天退换",
"title":"七天退换",
"type":3,
"url":"//img.alicdn.com/tps/i3/T1Vyl6FCBlXXaSQP_X-16-16.png"
}
],
"skuId":0,
"skuText":[
{
"name":"颜色分类",
"value":"欣欣子同款-mix灰14.0mm（轻混血感，真滴美迷糊了~）",
"visible":"SOLID"
},
{
"name":"度数",
"value":"200",
"visible":"SOLID"
}
],
"title":"美瞳年抛女半年抛月抛日抛棕色正品官网2022年新款隐形眼镜艾魅K"
},
"operations":[
{
"action":"a8",
"data":{
"crossOrigin":false,
"height":300,
"width":600
},
"dataUrl":"//trade.taobao.com/trade/operationConfirm.htm?data_url=%2F%2Frefund2.tmall.com%2Fdispute%2FsecondConfirm.do%3FbizOrderId%3D1749141123495230072%26attrKey%3DopenSHWY&from=listSoldItems",
"style":"t16",
"text":"打开售后入口",
"type":"operation"
},
{
"style":"t0",
"text":"保险服务",
"type":"operation",
"url":"//prod-baoxian.taobao.com/item/sellerList.htm?bizOrderId=1749141123495230072"
}
],
"priceInfo":{
"realTotal":"99.00"
},
"quantity":"1"
}
]
},
{
"buyer":{
"guestUser":false,
"id":2211594986958,
"memberUrl":"//member1.taobao.com/member/userProfile.jhtml?userID=tb961554905&sign=3d77a1b578bd683380308ce883a75ebf",
"nick":"tb961554905",
"operations":[
{
"action":"a14",
"imgUrl":"//gtd.alicdn.com/tps/i8/T1KNtuXc4rXXXXXXXX-12-12.png",
"style":"t0",
"title":"查询该买家订单",
"type":"operation",
"url":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1"
}
]
},
"extra":{
"batchSendGoods":1,
"closed":true,
"currency":"CNY",
"currencySymbol":"￥",
"disableCheckbox":false,
"inHold":false,
"isShowSellerService":false,
"sellerFlag":1
},
"id":"1749163874227985869",
"operations":[

],
"orderInfo":{
"archive":true,
"b2C":true,
"createTime":"2022-11-24 23:59:26",
"id":"1749163874227985869"
},
"payInfo":{
"actualFee":"13.90",
"icons":[
{
"linkTitle":"该订单来自您的手机淘宝店铺",
"linkUrl":"http://www.taobao.com/go/act/integrated/maijia-index.php?sprefer=symj27",
"type":3,
"url":"//img.alicdn.com/tps/i1/T1xRBqXdNAXXXXXXXX-46-16.png"
}
],
"postType":"(含快递:￥0.00)"
},
"statusInfo":{
"operations":[
{
"params":{
"qianNiuPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749163874227985869",
"solutionPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749163874227985869"
},
"style":"t16",
"text":"详情",
"type":"operation",
"url":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749163874227985869"
}
],
"text":"交易关闭",
"type":"t0"
},
"subOrders":[
{
"itemInfo":{
"extra":[
{
"name":"发货时间",
"value":"11月26日 00:00前发货",
"visible":"SOLID"
}
],
"itemUrl":"//trade.taobao.com/trade/detail/tradeSnap.htm?tradeID=1749163874227985869&snapShot=true",
"pic":"//img.alicdn.com/imgextra/i1/1583809483/O1CN018M1f1V2JvGfLnNQ5o_!!1583809483.jpg_sum.jpg",
"serviceIcons":[
{
"linkTitle":"正品保证",
"linkUrl":"//rule.tmall.com/tdetail-4400.htm",
"name":"正品保证",
"title":"正品保证",
"type":3,
"url":"//img.alicdn.com/tps/i2/T1SyeXFpliXXaSQP_X-16-16.png"
},
{
"linkTitle":"如实描述",
"linkUrl":"//www.taobao.com/go/act/315/xfzbz_rsms.php?ad_id=&am_id=130011830696bce9eda3&cm_id=&pm_id=",
"name":"如实描述",
"title":"如实描述",
"type":3,
"url":"//img.alicdn.com/tps/TB1PDB6IVXXXXaVaXXXXXXXXXXX.png"
},
{
"linkTitle":"七天退换",
"linkUrl":"//pages.tmall.com/wow/seller/act/seven-day",
"name":"七天退换",
"title":"七天退换",
"type":3,
"url":"//img.alicdn.com/tps/i3/T1Vyl6FCBlXXaSQP_X-16-16.png"
}
],
"skuId":0,
"skuText":[
{
"name":"颜色分类",
"value":"白桃香槟棕14.2mm",
"visible":"SOLID"
},
{
"name":"度数",
"value":"100",
"visible":"SOLID"
}
],
"title":"美瞳半年抛女棕色直径隐形眼镜月抛年抛日抛正品官网2022年新款TN"
},
"operations":[
{
"style":"t0",
"text":"保险服务",
"type":"operation",
"url":"//prod-baoxian.taobao.com/item/sellerList.htm?bizOrderId=1749163874227985869"
}
],
"priceInfo":{
"realTotal":"99.00"
},
"quantity":"1"
}
]
},
{
"buyer":{
"guestUser":false,
"id":2208347298844,
"memberUrl":"//member1.taobao.com/member/userProfile.jhtml?userID=tb243409190&sign=3f7be6fe9813fcdbe44500d765d4785c",
"nick":"tb243409190",
"operations":[
{
"action":"a14",
"imgUrl":"//gtd.alicdn.com/tps/i8/T1KNtuXc4rXXXXXXXX-12-12.png",
"style":"t0",
"title":"查询该买家订单",
"type":"operation",
"url":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1"
}
],
"phoneNum":"183********"
},
"extra":{
"batchSendGoods":1,
"currency":"CNY",
"currencySymbol":"￥",
"disableCheckbox":false,
"inHold":false,
"isShowSellerService":false,
"sellerFlag":0
},
"id":"1748473140797294488",
"operations":[

],
"orderInfo":{
"archive":true,
"b2C":true,
"createTime":"2022-11-24 23:58:49",
"id":"1748473140797294488"
},
"payInfo":{
"actualFee":"13.90",
"icons":[
{
"linkTitle":"该订单来自您的手机淘宝店铺",
"linkUrl":"http://www.taobao.com/go/act/integrated/maijia-index.php?sprefer=symj27",
"type":3,
"url":"//img.alicdn.com/tps/i1/T1xRBqXdNAXXXXXXXX-46-16.png"
}
],
"operations":[
{
"style":"t16",
"text":"查看物流",
"type":"operation",
"url":"//wuliu.taobao.com/user/order_detail_new.htm?trade_id=1748473140797294488&seller_id=1583809483"
}
],
"postType":"(含快递:￥0.00)"
},
"statusInfo":{
"operations":[
{
"params":{
"qianNiuPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1748473140797294488",
"solutionPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1748473140797294488"
},
"style":"t16",
"text":"详情",
"type":"operation",
"url":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1748473140797294488"
}
],
"text":"交易成功",
"type":"t0"
},
"subOrders":[
{
"itemInfo":{
"itemUrl":"//trade.taobao.com/trade/detail/tradeSnap.htm?tradeID=1748473140797294488&snapShot=true",
"pic":"//img.alicdn.com/imgextra/i3/1583809483/O1CN01y3pIhG2JvGdmTtpdi_!!1583809483.jpg_sum.jpg",
"serviceIcons":[
{
"linkTitle":"正品保证",
"linkUrl":"//rule.tmall.com/tdetail-4400.htm",
"name":"正品保证",
"title":"正品保证",
"type":3,
"url":"//img.alicdn.com/tps/i2/T1SyeXFpliXXaSQP_X-16-16.png"
},
{
"linkTitle":"如实描述",
"linkUrl":"//www.taobao.com/go/act/315/xfzbz_rsms.php?ad_id=&am_id=130011830696bce9eda3&cm_id=&pm_id=",
"name":"如实描述",
"title":"如实描述",
"type":3,
"url":"//img.alicdn.com/tps/TB1PDB6IVXXXXaVaXXXXXXXXXXX.png"
},
{
"linkTitle":"七天退换",
"linkUrl":"//pages.tmall.com/wow/seller/act/seven-day",
"name":"七天退换",
"title":"七天退换",
"type":3,
"url":"//img.alicdn.com/tps/i3/T1Vyl6FCBlXXaSQP_X-16-16.png"
}
],
"skuId":0,
"skuText":[
{
"name":"颜色分类",
"value":"水晶晶黑14.2mm【纯欲感玻璃珠】",
"visible":"SOLID"
},
{
"name":"度数",
"value":"275",
"visible":"SOLID"
}
],
"title":"美瞳半年抛女棕色直径隐形眼镜月抛年抛日抛正品官网2022年新款TN"
},
"operations":[
{
"action":"a8",
"data":{
"crossOrigin":false,
"height":300,
"width":600
},
"dataUrl":"//trade.taobao.com/trade/operationConfirm.htm?data_url=%2F%2Frefund2.tmall.com%2Fdispute%2FsecondConfirm.do%3FbizOrderId%3D1748473140797294488%26attrKey%3DopenSHWY&from=listSoldItems",
"style":"t16",
"text":"打开售后入口",
"type":"operation"
},
{
"style":"t0",
"text":"保险服务",
"type":"operation",
"url":"//prod-baoxian.taobao.com/item/sellerList.htm?bizOrderId=1748473140797294488"
}
],
"priceInfo":{
"realTotal":"99.00"
},
"quantity":"1"
}
]
},
{
"buyer":{
"guestUser":false,
"id":3404958832,
"memberUrl":"//member1.taobao.com/member/userProfile.jhtml?userID=t_1503842000048_0757&sign=7331f4e943bf865c7931022b1e042dc3",
"nick":"t_1503842000048_0757",
"operations":[
{
"action":"a14",
"imgUrl":"//gtd.alicdn.com/tps/i8/T1KNtuXc4rXXXXXXXX-12-12.png",
"style":"t0",
"title":"查询该买家订单",
"type":"operation",
"url":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1"
}
]
},
"extra":{
"batchSendGoods":1,
"closed":true,
"currency":"CNY",
"currencySymbol":"￥",
"disableCheckbox":false,
"inHold":false,
"isShowSellerService":false,
"sellerFlag":0
},
"id":"1749136515918953288",
"operations":[

],
"orderInfo":{
"archive":true,
"b2C":true,
"createTime":"2022-11-24 23:50:34",
"id":"1749136515918953288"
},
"payInfo":{
"actualFee":"12.80",
"icons":[
{
"linkTitle":"该订单来自您的手机淘宝店铺",
"linkUrl":"http://www.taobao.com/go/act/integrated/maijia-index.php?sprefer=symj27",
"type":3,
"url":"//img.alicdn.com/tps/i1/T1xRBqXdNAXXXXXXXX-46-16.png"
}
],
"postType":"(含快递:￥0.00)"
},
"statusInfo":{
"operations":[
{
"params":{
"qianNiuPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749136515918953288",
"solutionPCDetailUrl":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749136515918953288"
},
"style":"t16",
"text":"详情",
"type":"operation",
"url":"//trade.tmall.com/detail/orderDetail.htm?bizOrderId=1749136515918953288"
}
],
"text":"交易关闭",
"type":"t0"
},
"subOrders":[
{
"itemInfo":{
"extra":[
{
"name":"发货时间",
"value":"03月19日 14:18前发货",
"visible":"SOLID"
}
],
"itemUrl":"//trade.taobao.com/trade/detail/tradeSnap.htm?tradeID=1749136515918953288&snapShot=true",
"pic":"//img.alicdn.com/imgextra/i4/1583809483/O1CN01gxlQpo2JvGgVjpmwe_!!1583809483.jpg_sum.jpg",
"serviceIcons":[
{
"linkTitle":"正品保证",
"linkUrl":"//rule.tmall.com/tdetail-4400.htm",
"name":"正品保证",
"title":"正品保证",
"type":3,
"url":"//img.alicdn.com/tps/i2/T1SyeXFpliXXaSQP_X-16-16.png"
},
{
"linkTitle":"如实描述",
"linkUrl":"//www.taobao.com/go/act/315/xfzbz_rsms.php?ad_id=&am_id=130011830696bce9eda3&cm_id=&pm_id=",
"name":"如实描述",
"title":"如实描述",
"type":3,
"url":"//img.alicdn.com/tps/TB1PDB6IVXXXXaVaXXXXXXXXXXX.png"
},
{
"linkTitle":"七天退换",
"linkUrl":"//pages.tmall.com/wow/seller/act/seven-day",
"name":"七天退换",
"title":"七天退换",
"type":3,
"url":"//img.alicdn.com/tps/i3/T1Vyl6FCBlXXaSQP_X-16-16.png"
}
],
"skuId":0,
"skuText":[
{
"name":"颜色分类",
"value":"生椰拿铁14.5mm（大美目黑上眼奶fufu的 直男一眼沦陷~）",
"visible":"SOLID"
},
{
"name":"度数",
"value":"0【每周上新花色，记得收藏加购】",
"visible":"SOLID"
}
],
"title":"美瞳年抛女半年抛月抛日抛棕色正品官网2022年新款隐形眼镜艾魅K"
},
"operations":[
{
"style":"t0",
"text":"保险服务",
"type":"operation",
"url":"//prod-baoxian.taobao.com/item/sellerList.htm?bizOrderId=1749136515918953288"
}
],
"priceInfo":{
"realTotal":"99.00"
},
"quantity":"1"
}
]
}
],
"page":{
"currentPage":1,
"globalCodes":[

],
"pageSize":15,
"prefetchCount":31,
"queryForTitle":false,
"totalNumber":15,
"totalPage":1
},
"query":{
"action":"itemlist/SoldHisQueryAction",
"auctionType":0,
"buyerNick":"",
"cartItemDOList":[

],
"close":0,
"dateBegin":0,
"dateEnd":0,
"extra":{

},
"lastStartRow":"ha3,1749159014619698484,0,15",
"pageNum":1,
"pageSize":15,
"payDateBegin":0,
"payDateEnd":0,
"queryMore":false,
"queryOrder":"desc",
"rxAuditFlag":0,
"rxElectronicAllFlag":0,
"rxElectronicAuditFlag":0,
"rxHasSendFlag":0,
"rxOldFlag":0,
"rxSendFlag":0,
"rxSuccessflag":0,
"rxWaitSendflag":0,
"sellerMemo":0,
"tabCode":"before3Months",
"tradeTag":0,
"useCheckcode":false,
"useOrderInfo":false
},
"queryOption":{
"aftersaleType":[
{
"label":"全部",
"value":"ALL"
},
{
"label":"买家投诉",
"value":"BUYER_SUIT"
},
{
"label":"我已投诉",
"value":"SELLER_SUIT"
},
{
"label":"退款中",
"value":"REFUNDING"
}
],
"appNameList":[
{
"label":"全部订单",
"value":"ALL"
},
{
"label":"天猫APP",
"value":"tmall"
}
],
"bizType":[
{
"label":"全部",
"value":"ALL"
},
{
"label":"机票订单",
"value":"1400"
},
{
"label":"数字订单",
"value":"1500"
},
{
"label":"理财订单",
"value":"3000"
},
{
"label":"网游订单",
"value":"900"
},
{
"label":"酒店订单",
"value":"710"
},
{
"label":"保险订单",
"value":"1102"
},
{
"label":"企采订单",
"value":"corpMarket"
},
{
"label":"送礼订单",
"value":"giftMarket"
},
{
"label":"租赁订单",
"value":"leaseMarket"
},
{
"label":"境外订单",
"value":"oversea"
}
],
"commonTradeType":[
{
"label":"所有类型",
"value":0
},
{
"label":"一口价",
"value":1
},
{
"label":"拍卖",
"value":2
}
],
"logisticsType":[
{
"label":"全部",
"value":"ALL"
},
{
"label":"货到付款",
"value":"COD"
},
{
"label":"卖家物流",
"value":"SELLER_PAYED"
}
],
"orderStatus":[
{
"label":"全部",
"value":"ALL"
},
{
"label":"等待买家付款",
"value":"NOT_PAID"
},
{
"label":"买家已付款",
"value":"PAID"
},
{
"label":"卖家已发货",
"value":"SEND"
},
{
"label":"交易成功",
"value":"SUCCESS"
},
{
"label":"交易关闭",
"value":"DROP"
},
{
"label":"待付款和待发货订单",
"value":"NOT_PAID_AND_NOT_SEND"
},
{
"label":"未完成的订单",
"value":"NOT_FINISHED"
},
{
"label":"退款中的订单",
"value":"REFUNDING"
},
{
"label":"定金已付",
"value":"FRONT_PAID"
},
{
"label":"异常订单",
"value":"EXCEPTIONAL"
}
],
"preSaleTradeType":[
{
"label":"全部",
"value":"ALL"
},
{
"label":"预付款已付未确认",
"value":"waitConfirm"
},
{
"label":"已确认未付尾款",
"value":"waitPayWeikuan"
}
],
"rateStatus":[
{
"label":"全部",
"value":"ALL"
},
{
"label":"需我评价",
"value":"I_HAS_NOT_COMMENT"
},
{
"label":"我已评价",
"value":"I_HAS_COMMENT"
},
{
"label":"对方已评",
"value":"OTHER_HAS_COMMENT"
},
{
"label":"双方已评",
"value":"ALL_COMMENT"
}
]
},
"tabs":[
{
"code":"latest3Months",
"herf":"/trade/itemlist/list_sold_items.htm?userSwitch=1",
"text":"近三个月订单"
},
{
"code":"waitBuyerPay",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=NOT_PAID&tabCode=waitBuyerPay",
"text":"等待买家付款"
},
{
"code":"waitSend",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=PAID&tabCode=waitSend",
"text":"等待发货"
},
{
"code":"haveSendGoods",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=SEND&tabCode=haveSendGoods",
"text":"已发货"
},
{
"code":"refunding",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=REFUNDING&tabCode=refunding",
"text":"退款中"
},
{
"code":"waitRate",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&commentStatus=I_HAS_NOT_COMMENT&tabCode=waitRate",
"text":"需要评价"
},
{
"code":"success",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=SUCCESS&tabCode=success",
"text":"成功的订单"
},
{
"code":"closed",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=DROP&tabCode=closed",
"text":"关闭的订单"
},
{
"code":"before3Months",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldHisQueryAction&event_submit_do_query=1&tabCode=before3Months",
"selected":true,
"text":"三个月前订单"
},
{
"code":"drugPending",
"herf":"/trade/itemlist/list_sold_items.htm?action=itemlist/SoldQueryAction&event_submit_do_query=1&auctionStatus=AUDIT&tabCode=drugPending",
"text":"待处理的处方药订单"
}
]
}