<?php

/*Do not edit this file manually. This copy of global file is overwritten by extensions editor.*/

$installed_extensions = array (
  2 => 
  array (
    'package' => 'rebate_purchase',
    'name' => '采购返利',
    'version' => '0.1.1',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rebate_purchase',
    'active' => 1,
    'description' => '-- 医药流通企业_返利折让系统 --',
    'SubPath' => 
    array (
      0 => 'rebate_purchase',
    ),
  ),
  3 => 
  array (
    'package' => 'rebate_sales',
    'name' => '销售返利',
    'version' => '0.1.1',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rebate_sales',
    'active' => 1,
    'description' => '-- 医药流通企业_返利折让系统_销售返利   --',
    'SubPath' => 
    array (
      0 => 'rebate_sales',
    ),
  ),
  4 => 
  array (
    'package' => 'baseinfo',
    'name' => '基本信息扩展',
    'version' => '0.1.1',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/baseinfo',
    'active' => 1,
    'description' => '-- 医药行业基础信息扩展 --',
    'SubPath' => 
    array (
      0 => 'baseinfo',
    ),
  ),
);
