<?php

/*Do not edit this file manually. This copy of global file is overwritten by extensions editor.*/

$installed_extensions = array (
  1 => 
  array (
    'package' => 'demo',
    'name' => 'demo_mod',
    'version' => '0.1.1',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/demo',
    'active' => 1,
  ),
);
